language: java
install:
- echo "Installed"
script:
- sh publish.sh
after_success:
- sh deploy.sh
env:
  global:
  - DITAMAP=test.ditamap
  - ANT_OPTS=-Xmx1024M
  - secure: awCgXImOcBDjhSQyDB8BXt/N4tTtJnQH97FowXioLOrSJQ3fTf1H8WSvmq4q+7TLDOh9b2ABufarssMY8TUa3a4r7hmdbhtl6SNlFogKZ/llXNy86QRiR+SPSp/QDQ4UiWUKNqfyjkA9B0M7JvW3rzVgvwruoit91b3jLe4oHhKuy8qOUqrAKlp5HIp8jqpWPaN/R7hgF6fPQ+frZLWBDVti3CzH9gN1wetk2Je8pu74nyNPl+wMLd3AMN3IBc4q2bjwBL8CtT26C5MdD1jwKQt4EiaU7Q2IBCR9DEd9s5oLAjJJtivPZsUtsviVISx5RqSycF9KTNib0WJtByR7xnTo1l32rnrt2aCFV4+iLc71T5XWZ+4r6Tu+YDBzTAcV9zgILlKZRJWM1T8uy8FPn4aiFJumcbnJuRV/11kvDD5EWTIEktOtTC6NGUL1mmzCzpvLPsMENgzLVdYkODDr+U8ONrWS1wwsliMMHbcQ7PojqYrFAA5kOt6p2u6OJx7q1QLiOE92nVYBQ0HYtzJFb8yaPT0f0pVFGEuqpRSWoCtsXQ+wb7Sk15twpOl20K1Ixh9QqyYlN48avaeRkShmLAtmqq86u9NEDQQKAWZpXy0QM1RHdHSJnVGAjy4Xh5qWxHe/+/FkfJo45qZfJNCAlcGToc6DFH+7cKkL2q3MT4o=
