language: java
install:
- echo "Installed"
script:
- sh publish.sh
after_success:
- sh deploy.sh
env:
  global:
  - DITAMAP=test.ditamap
  - ANT_OPTS=-Xmx1024M
  - secure: l3KEOApIrXdnq/b2NuNcDF4zDJnZudP5ZTey1SN9pcXd5w/bYwEsv3WTRsnDWb/l0tCFe4rNpHnqIPej5AbxfJ2z6r46nuz+sE5esI+lrAmqHKtASq8tAlkduiA33WXqBA6NMLEE+Dq+lA4zbrmTkINT6WC6O3maf50XvugoR1tqJzB7FLujZncYJePodW/cMq7l208VGmXEDnHccAwlQDISWEbfKaHmktJ6Tt/8hNse2daaWgIH+Wbm17nHVUXieAmOEeq9SPitDTiIha1LqNbSdF1DliK278UcNU/fCj90BKRmwfcz/3kw8/IROfxVonEA313N/qHlS6O9ouEOchoxMtemq+z2CO15+wgkzE6yRK6oXQxtfcWvOXXg094JOYl86MVWej9OUJU3sBmi4645iv1AHzgnUEB4gS08aJLXeZXSHSO7E2bNpXIhhKa1in/wtrY3uSzehWQWDnYtLd1KZqqtxm/nuHS5BKxJsC/DBcIXpkdKeFs67GcSJs+gKkxqwhpjNiQUFF91HfiSbVrB0l3w6ACqhxNFqvFo/enS9vdmlR66lEEhHbOXTR2XSxyVYMYhWhtI3ei01DyqWRqw9iAbBQzlemDkHn08TaqbqrCrgrHyzB5iuBsmo0gG03mYDogbdTwVDzx/i3d8A0hGAoGE/j3JribAku3D+8k=
