language: java
install:
- echo "Installed"
script:
- sh publish.sh
after_success:
- sh deploy.sh
env:
  global:
  - DITAMAP=test.ditamap
  - ANT_OPTS=-Xmx1024M
  - secure: RPkCfe6apmuBpl/efmW/wPsx6+i6Yt5+7lfgyZljrx5W4YdiJLUDVQGc7kEik/me3c4cFz0b7XG7TfqSOwxt7gJ8NrfoCasLDEvfGT5Owg08CiMp06BbczrEHKRKIbmZhy9XM1NwUpK9IO8gibnzj9P3Hoh+Gbx6xaOKgMvHtNnB7ZsprK+ostnSzEasYCY7f9kHHk1GrWYFdTLjUeUeva/6d0Xx3vSxeL4DaDV7i8L+glqgWkVOE7BFIKPGKKDz0MO7AeI0Dih9zvCKPPtNVCCPWgBZsGe2Q69dKwDzZdqtaMQBGunhW6vdfjYc0u0UCSGwCiaMUjO6HdBxlwkhLRx9iWcgtRG2ca532MgGciIT91a6+I+pnXZgWnxVIn8OxiCAhnk23DiIkRcTL+SASSBBvBUpj2KLYk4xvGK2SH2jnXCUaZ17R5YKwKhUrbb4nUkpiLQV1uZbmlrCtZ86K7crTSeHPHOUyVJ7aqOEjkj/swOYMr4A8c3R0mFvdjM6RGYnlKDVMwEppoPj8wtAcjng55Nl5s/auIR/u3k08xnuouUiLrfH+LIqicF4ytIFfAa2Qnv3FR+lZiOHmnvd/B7EhZTNoZOdhX7MhGUlsKcVytG8NYbhRm4p9uum7MjMKWhF87kMZnDXIgARde7i12Pvpr9lktnExwOmCwkcIrc=
