language: java
install:
- echo "Installed"
script:
- sh publish.sh
after_success:
- sh deploy.sh
env:
  global:
  - DITAMAP=test.ditamap
  - ANT_OPTS=-Xmx1024M
  - secure: g48obPNSFImr2M1vzjQ8Bu9/n/viIE4YxBPwxOkln26Ln2KOzzkDHwW7nST3kjkGbwNZjnq35jprQpaqaU1DY2aTdSVccDQMJW7QO89fzXORYWrd4E7oas6jgI8Kwb5ehjrO2kop9iqgCQQGOajjfI/foGKxNWV6sEmOJYqmR5gZrmmDtXDh8WJ5Wx7eXloEHecnE/xI1aPN1+7u6x3qXDCwYEt4JUvQ4siVtGkhiUHTgJ7ah2SsFYJWwtgAtBWUWfQKC7gBmbCNj0MNf6iXOwe3ZhzEu6LhdxMtHMneXx5EMFYMT9DQeaTtsdJVjuDsdAeVYxdK8XvlEB+wko+eEPMCp61zOcI1hgkTTQSyW/eQ6k4pHOjgKO9/H1s7ZSX9dI4G2HdAbGLKO2bJEmA3k5/c+Br5AyKj2vIaXNdWkwIE96nRb08PARac8ZXH2PDUwfguy/A6ALpwV6sH+R8dQ9GuSgjk6S/cN0jUuP9eDDciwoxKBIuaspA7On+FJk6tIqdkHSPd58Pfjhw1UtmIkn2wFWGqCERNGz5FB+pWHvYdf5e3nVPxGHcKoz3YGcPBrWlmmVFGjY8GmhCNs0ffIS/KgYZC+UEpvP1AaiO8Z5nH2d96enAVpKhSL1VzwLsgnskL5RkTJAcV+gB4BFqCc0+wZbiJNxcWP2/zdLw5M/g=
