language: java
install:
- echo "Installed"
script:
- sh publish.sh
after_success:
- sh deploy.sh
env:
  global:
  - DITAMAP=test.ditamap
  - ANT_OPTS=-Xmx1024M
  - secure: ztfoeHFC3PRWi8qSG9T+8S0tSIR1O2J2w+VVGTq+qXOpME0FBoLk55PDKtNjBJgZfhIZnQYTR5A8RJpLvr9rhReZV39efjFnvOGyNw1mdAH1uc/CLx4cOYkb5otRI80noyv8q2lDCp+UMNYkXvkWIMdNjlg8r/D/o8aomfx0ZBIdZa4hPdVsTbm8CHT1zgYNiLelSAKZLYYv7CPj24wxrhoGFfki7hTROo/bFffDRViyqfEf465ZPCYb3sB8s4aFTcxtE8hFBwwwBfvkR9rpbHbVLEObO7gyy3IgJ0k6x+vBlilZch9Wr5IoVZ4Bpqy631gzWqIlPh62AkOs4wUEBqOR+ARJfEC2D0Tf+GcuK2pvgb6IKkDE4y41DHCJ530V1AEi6VGFClyvOLK8kbCYMR/dkEf+flLTAXYsrIlcOQKFfph+3EKnWBIxY2B9Fpcj2hZmS2Je0UajMxVmvdG6qcF1m3axh6Vmh+EWZuTZCZVqBkfZHmr6FCdGOAU/WbkzBkhZMdi8fy3ABaZzlQo/AGAr+zgywiDU9lKszFmBcPrxjDiVteFG7EcxBHcK1dOZYrWOTmjsSjpL6CXbNN/p9TTRhI51dHw+KcG/fd9kxA2CWYUa5J5NbVjt6CqFb4TjsbxAKntt+Tot+i+B5ptW7CLpUnoOGNpZasHlczFNKM8=
